### ISSUE TITLE
How to use current branch

### ISSUE THREAD

**Issue by irondave** [jaos/slapt-src#2]
How can I use slapt-src with slackbuilds in the repo https://github.com/Ponce/slackbuilds for slackbuilds for the current branch of slackware?

**Comment by jaos** [comment]
slapt-src requires the manifest files SLACKBUILDS.TXT and CHECKSUMS.md5 as found here: https://slackbuilds.org/slackbuilds/14.2/

http://cgit.ponce.cc/slackbuilds/tree/ is only setup for manual slackbuild support.
