### ISSUE TITLE
doinst.sh improvements

### ISSUE THREAD

**Issue by scop** [jaos/slapt-src#4]
I'm currently making slapt-get and slapt-src available for the test suite of https://github.com/scop/bash-completion/. For now I'm doing it by setting them up in a Debian 10 container, just unpacking your slack64 binary tarballs there. This ugliness seems to work at least to some extent -- as much as I think I'll need it for to test completions -- but I believe I ran into a buglet in slapt-src's doinst.sh script. I didn't find it here in the repo so here goes a patch in a regular issue.

The patch is against the install/doinst.sh script found inside https://software.jaos.org/slackpacks/slackware64-14.2/slapt-src/slapt-src-0.3.2i-x86_64-1.tgz, first formatted for patch readability.

```patch
+++ install/doinst.sh	2020-05-09 07:41:21.814205269 +0300
@@ -3,5 +3,6 @@
 fi
 if [ ! -f etc/slapt-get/slapt-srcrc ]; then
     mv -f etc/slapt-get/slapt-srcrc.new etc/slapt-get/slapt-srcrc
-    diff -q etc/slapt-get/slapt-srcrc etc/slapt-get/slapt-srcrc.new >/dev/null 2>&1 && rm etc/slapt-get/slapt-srcrc.new
+else
+    ! diff -q etc/slapt-get/slapt-srcrc etc/slapt-get/slapt-srcrc.new >/dev/null 2>&1 || rm etc/slapt-get/slapt-srcrc.new
 fi
```

This improves two things:
- does the diff only when slapt-srcrc existed, otherwise there's no use doing it
- turns the `foo && bar` in the diff to `! foo || bar` which is equivalent otherwise, but makes the script exit with a zero exit status if there were no errors

As you can see, I'm completely clueless wrt slackware, but hope this is useful. I'm going to work around this in my above mentioned docker build for now by ignoring slapt-src's doinst,sh exit status.

**Comment by jaos** [comment]
Thanks for the note and fix.  I have some slack containers published if that helps you test. https://hub.docker.com/r/gnujaos/
