### ISSUE TITLE
slapt-src  no see build upgrades

### ISSUE THREAD

**Issue by wifislax-ng** [jaos/slapt-src#5]
Hi , i noticed slapt-src (last version) , no see build upgrades.

Only see version upgrades , but if same version , then nothing offer.

Example , you have pkg-1.1-build1   and slackbuilds release pkg-1.1build2 , slapt-src no see that as update available.

Only when version changes not when builds upgrade , i notices this week, when see avahi , up to build5 to build6 addind patches for some security problems, but slapt-src - no offers.

I do

slapt-src  -U (to update base slackbuilds to latest)
slapt-src -u  (to find upgrades)

i use slackbuilds for 15.0 , my system is slackware64-15.0

**Comment by jaos** [comment]
Only the info file is parsed. When the build script is edited that's not in the metadata. Upgrade is a helper for new release versions.

If you know a build script has been updated (from changelog or other notification mechanisms) you can rebuild it.

**Comment by wifislax-ng** [comment]
If you think , "missing" updates are okey , then close this issue, no problem.
