### ISSUE TITLE
Implementation of some blacklist mechanism ?

### ISSUE THREAD

**Issue by wifislax-ng** [jaos/slapt-src#6]
Hi , some times i use erik (Alienb0b) packages , and when i try to see updates with

slapt-src -U

Then offer as example "libreoffice" from slackbuilds but i prefer stay on alienb0b version.

Can we gent some "blacklist" mechanism ? to blacklist for example [0-9]alienbob , to no upgrade this.

Thanks for the work.

**Comment by jaos** [comment]
- We might be able to do an exclude list. But the upgrade option is really dumb on purpose since it crosses binary and source package boundaries and the tagging you mention is really non deterministic.

**Comment by wifislax-ng** [comment]
No see incremetal build updates ,but see and destroy other packages not from sbo ... thanks for this fantastic destructive tool.

Close the issue and do nothing again. :=)
