### ISSUE TITLE
Is it possible to do a package version check?

### ISSUE THREAD

**Issue by blackcross86** [jaos/slapt-src#7]
With slapt-src --feth I clone the project, edit the version, but with slapt-src --build it downloads the old version. Is it possible to make it download it if there is a new version?

Or does it only work for the repository sbo?and if you update locally, then only manually

**Comment by jaos** [comment]
Yeah, if you are customizing the slackbuild script or contents then you can run the build script directly. There isn't much utility in wrapping upgradepkg/installpkg from there.

**Comment by blackcross86** [comment]
Sorry, but thanks for the reply. The utilities are very useful and I want to see new features in the new year. Not only in this utility, but also in others that you develop.
