### ISSUE TITLE
The option -U or --upgrade tries to update package not installed with it

### ISSUE THREAD

**Issue by DidierSpaier** [jaos/slapt-src#8]
Hello,

This could be considered a feature request rather than a problem.

I have this line in /etc/slapt-get/slapt-srcrc:
SOURCE=https://slackbuilds.org/slackbuilds/15.0/

When I run slapt-src -u and then slapt-src --upgrade I get a large list of packages to fetch and/or upgrade, even though none of them have been build/installed with slapt-src (attached file [slapt-src.txt](https://github.com/jaos/slapt-src/files/12433230/slapt-src.txt)).

Currently, slapt-src looks at all installed packages (as listed by "slapt-get --installed") and compares their versions with the version of the package with the same short name in the repository listed in /etc/slapt-get/slapt-src, and if they differ it triggers an upgrade, possibly replacing a package installed by slapt-get with one that may have a different content (because of different build options, for example), possibly a dependency that was expected at a certain version of another package.
 
To avoid this, I would like slapt-src to only update packages that it has built and installed.  One way would be to keep a list of packages installed by slapt-src (updated when packages are installed or removed). Another way could be to select for possible upgrade only packages with a specific tag, such as SBo, or perhaps one of several tags, the list of which could be written in slapt-srcrc by the user.

**Comment by jaos** [comment]
Leaving a breadcrumb of what was built via slapt-src wouldn't cover all use cases (someone doing manual builds etc). 

We could add an option to ignore packages known to slapt-get to avoid auto adding them to the convenience upgrade option (although this convenience option is becoming a real source of gotchas for a lot of folks).

I have a quick mock up in the skip-installable (working title... suggestions welcome) branch: https://github.com/jaos/slapt-src/commit/f67f47be1664406c5907328a5acc276507ff3ab0

**Comment by jaos** [comment]
Leaving a breadcrumb of what was built via slapt-src wouldn't cover all use cases (someone doing manual builds etc).

We could add an option to ignore packages known to slapt-get to avoid auto adding them to the convenience upgrade option (although this convenience option is becoming a real source of gotchas for a lot of folks).

I have a quick mock up in the skip-installable (working title... suggestions welcome) branch: jaos/slapt-src@f67f47b

**Comment by jaos** [comment]
Leaving a breadcrumb of what was built via slapt-src wouldn't cover all use cases (someone doing manual builds etc).

We could add an option to ignore packages known to slapt-get to avoid auto adding them to the convenience upgrade option (although this convenience option is becoming a real source of gotchas for a lot of folks).

I have a quick mock up in the skip-installable (working title... suggestions welcome) branch: jaos/slapt-src@6e6cca57fbfa9a93f2ce6d427ab3deae0b8f1014

**Comment by DidierSpaier** [comment]
Just made a quick test, with -S -U the output is empty, so seems to work, thanks. Will do more tests later as it's 2:30 AM here :)

Just a small caveat: a custom package not in any repository mentioned in slapt-getrc will be upgraded, I assume. But that's probably a minor inconvenience as users could put it in a custom repository, if they know how to set it up.

**Comment by DidierSpaier** [comment]
I confirm that "slapt-src -U -S"  works as expected wrt restrictions to packages not under the  slapt-get radar but then after having fetched the needed files the new packages fail to be built with an error message like for instance:

Failed to chdir to network/zoom-linux/

However in this example slapt-src -i zoom-linux does build the new package and perform the upgrade. 

This is on Slint 15.0, I did not try in another distribution.

**Comment by jaos** [comment]
> I confirm that "slapt-src -U -S"  works as expected wrt restrictions to packages not under the  slapt-get radar but then after having fetched the needed files the new packages fail to be built with an error message like for instance:
> 
> 
> 
> Failed to chdir to network/zoom-linux/
> 
> 
> 
> However in this example slapt-src -i zoom-linux does build the new package and perform the upgrade. 

Thanks! I think that's a simple, quick fix to reset the working dir properly.

**Comment by jaos** [comment]
Quick fix: https://github.com/jaos/slapt-src/commit/27debba272117ae17a625eb8a28b48346f8eff43. I think this is good.

**Comment by DidierSpaier** [comment]
I made a few tests and yes this patch LGTM, so thanks for the quick fix, Jason.

I'd  welcome a merge with the main branch and a new tag :D

**Comment by jaos** [comment]
Thanks, Didier!

Merged. I pushed updated translations so I'll wait for those to get updated and make a release.
